---
title: "Learning Text Analytics in R"
output: github_document
---


# Learning TextAnalytics in R

If you work in data science or analytics, then you can't survive without data. At a basic level, you would be using Excel to create adhoc reports or charts for better business understanding. If you know some coding skills, then you would  also use R or Python to solve your business problem at scale. In doing so, most of the time you have to deal with data in tabular or matrix format. This is known as structured data.

But about a situation when you have to deal with the text data. This data is too growing at a rapid speed along with other types of business data which is in structured format. If this un-structured data in used properly, then business can gain invaluable insights for itself and for its competition.  

Today we will talk about this data and what all we can do with it. 

## This Tutorial will cover following topics in R 


- Text data manipulation
- Sentiment Analysis
- Term Frequency - Inverse Document Frequency
- N-grams
- Tidying Data
- Topic Modeling
- Text Analysis Application


